#include <QtGlobal>
// Automatically generated by extract_strings.py
#ifdef __GNUC__
#define UNUSED __attribute__((unused))
#else
#define UNUSED
#endif
static const char UNUSED *wacoins_strings[] = {QT_TRANSLATE_NOOP("wacoins-core", ""
"Unable to bind to port %d on this computer.  WACoins is probably already "
"running."),
QT_TRANSLATE_NOOP("wacoins-core", "Warning: Disk space is low  "),
QT_TRANSLATE_NOOP("wacoins-core", "WACoins version"),
QT_TRANSLATE_NOOP("wacoins-core", "Usage:"),
QT_TRANSLATE_NOOP("wacoins-core", "Send command to -server or wacoinsd"),
QT_TRANSLATE_NOOP("wacoins-core", "List commands"),
QT_TRANSLATE_NOOP("wacoins-core", "Get help for a command"),
QT_TRANSLATE_NOOP("wacoins-core", "Options:"),
QT_TRANSLATE_NOOP("wacoins-core", "Specify configuration file (default: wacoins.conf)"),
QT_TRANSLATE_NOOP("wacoins-core", "Specify pid file (default: wacoins.pid)"),
QT_TRANSLATE_NOOP("wacoins-core", "Generate coins"),
QT_TRANSLATE_NOOP("wacoins-core", "Don't generate coins"),
QT_TRANSLATE_NOOP("wacoins-core", "Start minimized"),
QT_TRANSLATE_NOOP("wacoins-core", "Show splash screen on startup (default: 1)"),
QT_TRANSLATE_NOOP("wacoins-core", "Specify data directory"),
QT_TRANSLATE_NOOP("wacoins-core", "Set database cache size in megabytes (default: 25)"),
QT_TRANSLATE_NOOP("wacoins-core", "Set database disk log size in megabytes (default: 100)"),
QT_TRANSLATE_NOOP("wacoins-core", "Specify connection timeout (in milliseconds)"),
QT_TRANSLATE_NOOP("wacoins-core", "Connect through socks4 proxy"),
QT_TRANSLATE_NOOP("wacoins-core", "Allow DNS lookups for addnode and connect"),
QT_TRANSLATE_NOOP("wacoins-core", "Listen for connections on <port> (default: 22441 or testnet: 22443)"),
QT_TRANSLATE_NOOP("wacoins-core", "Maintain at most <n> connections to peers (default: 125)"),
QT_TRANSLATE_NOOP("wacoins-core", "Add a node to connect to and attempt to keep the connection open"),
QT_TRANSLATE_NOOP("wacoins-core", "Connect only to the specified node"),
QT_TRANSLATE_NOOP("wacoins-core", "Find peers using internet relay chat (default: 0)"),
QT_TRANSLATE_NOOP("wacoins-core", "Accept connections from outside (default: 1)"),
QT_TRANSLATE_NOOP("wacoins-core", "Set language, for example \"de_DE\" (default: system locale)"),
QT_TRANSLATE_NOOP("wacoins-core", "Find peers using DNS lookup (default: 1)"),
QT_TRANSLATE_NOOP("wacoins-core", "Threshold for disconnecting misbehaving peers (default: 100)"),
QT_TRANSLATE_NOOP("wacoins-core", ""
"Number of seconds to keep misbehaving peers from reconnecting (default: "
"86400)"),
QT_TRANSLATE_NOOP("wacoins-core", "Maximum per-connection receive buffer, <n>*1000 bytes (default: 10000)"),
QT_TRANSLATE_NOOP("wacoins-core", "Maximum per-connection send buffer, <n>*1000 bytes (default: 10000)"),
QT_TRANSLATE_NOOP("wacoins-core", "Use Universal Plug and Play to map the listening port (default: 1)"),
QT_TRANSLATE_NOOP("wacoins-core", "Use Universal Plug and Play to map the listening port (default: 0)"),
QT_TRANSLATE_NOOP("wacoins-core", "Fee per KB to add to transactions you send"),
QT_TRANSLATE_NOOP("wacoins-core", "Accept command line and JSON-RPC commands"),
QT_TRANSLATE_NOOP("wacoins-core", "Run in the background as a daemon and accept commands"),
QT_TRANSLATE_NOOP("wacoins-core", "Use the test network"),
QT_TRANSLATE_NOOP("wacoins-core", "Output extra debugging information"),
QT_TRANSLATE_NOOP("wacoins-core", "Prepend debug output with timestamp"),
QT_TRANSLATE_NOOP("wacoins-core", "Send trace/debug info to console instead of debug.log file"),
QT_TRANSLATE_NOOP("wacoins-core", "Send trace/debug info to debugger"),
QT_TRANSLATE_NOOP("wacoins-core", "Username for JSON-RPC connections"),
QT_TRANSLATE_NOOP("wacoins-core", "Password for JSON-RPC connections"),
QT_TRANSLATE_NOOP("wacoins-core", "Listen for JSON-RPC connections on <port> (default: 22442)"),
QT_TRANSLATE_NOOP("wacoins-core", "Allow JSON-RPC connections from specified IP address"),
QT_TRANSLATE_NOOP("wacoins-core", "Send commands to node running on <ip> (default: 127.0.0.1)"),
QT_TRANSLATE_NOOP("wacoins-core", ""
"Execute command when the best block changes (%s in cmd is replaced by block "
"hash)"),
QT_TRANSLATE_NOOP("wacoins-core", "Upgrade wallet to latest format"),
QT_TRANSLATE_NOOP("wacoins-core", "Set key pool size to <n> (default: 100)"),
QT_TRANSLATE_NOOP("wacoins-core", "Rescan the block chain for missing wallet transactions"),
QT_TRANSLATE_NOOP("wacoins-core", "How many blocks to check at startup (default: 2500, 0 = all)"),
QT_TRANSLATE_NOOP("wacoins-core", "How thorough the block verification is (0-6, default: 1)"),
QT_TRANSLATE_NOOP("wacoins-core", ""
"\n"
"SSL options: (see the WACoins Wiki for SSL setup instructions)"),
QT_TRANSLATE_NOOP("wacoins-core", "Use OpenSSL (https) for JSON-RPC connections"),
QT_TRANSLATE_NOOP("wacoins-core", "Server certificate file (default: server.cert)"),
QT_TRANSLATE_NOOP("wacoins-core", "Server private key (default: server.pem)"),
QT_TRANSLATE_NOOP("wacoins-core", ""
"Acceptable ciphers (default: TLSv1+HIGH:!SSLv2:!aNULL:!eNULL:!AH:!3DES:"
"@STRENGTH)"),
QT_TRANSLATE_NOOP("wacoins-core", "This help message"),
QT_TRANSLATE_NOOP("wacoins-core", "Usage"),
QT_TRANSLATE_NOOP("wacoins-core", ""
"Cannot obtain a lock on data directory %s.  WACoins is probably already "
"running."),
QT_TRANSLATE_NOOP("wacoins-core", "WACoins"),
QT_TRANSLATE_NOOP("wacoins-core", "Loading addresses..."),
QT_TRANSLATE_NOOP("wacoins-core", "Error loading addr.dat"),
QT_TRANSLATE_NOOP("wacoins-core", "Loading block index..."),
QT_TRANSLATE_NOOP("wacoins-core", "Error loading blkindex.dat"),
QT_TRANSLATE_NOOP("wacoins-core", "Loading wallet..."),
QT_TRANSLATE_NOOP("wacoins-core", "Error loading wallet.dat: Wallet corrupted"),
QT_TRANSLATE_NOOP("wacoins-core", "Error loading wallet.dat: Wallet requires newer version of WACoins"),
QT_TRANSLATE_NOOP("wacoins-core", "Wallet needed to be rewritten: restart WACoins to complete"),
QT_TRANSLATE_NOOP("wacoins-core", "Error loading wallet.dat"),
QT_TRANSLATE_NOOP("wacoins-core", "Cannot downgrade wallet"),
QT_TRANSLATE_NOOP("wacoins-core", "Cannot initialize keypool"),
QT_TRANSLATE_NOOP("wacoins-core", "Cannot write default address"),
QT_TRANSLATE_NOOP("wacoins-core", "Rescanning..."),
QT_TRANSLATE_NOOP("wacoins-core", "Done loading"),
QT_TRANSLATE_NOOP("wacoins-core", "Invalid -proxy address"),
QT_TRANSLATE_NOOP("wacoins-core", "Invalid amount for -paytxfee=<amount>"),
QT_TRANSLATE_NOOP("wacoins-core", ""
"Warning: -paytxfee is set very high.  This is the transaction fee you will "
"pay if you send a transaction."),
QT_TRANSLATE_NOOP("wacoins-core", "Error: CreateThread(StartNode) failed"),
QT_TRANSLATE_NOOP("wacoins-core", "To use the %s option"),
QT_TRANSLATE_NOOP("wacoins-core", ""
"%s, you must set a rpcpassword in the configuration file:\n"
" %s\n"
"It is recommended you use the following random password:\n"
"rpcuser=wacoinsrpc\n"
"rpcpassword=%s\n"
"(you do not need to remember this password)\n"
"If the file does not exist, create it with owner-readable-only file "
"permissions.\n"),
QT_TRANSLATE_NOOP("wacoins-core", "Error"),
QT_TRANSLATE_NOOP("wacoins-core", "An error occured while setting up the RPC port %i for listening: %s"),
QT_TRANSLATE_NOOP("wacoins-core", ""
"You must set rpcpassword=<password> in the configuration file:\n"
"%s\n"
"If the file does not exist, create it with owner-readable-only file "
"permissions."),
QT_TRANSLATE_NOOP("wacoins-core", ""
"Warning: Please check that your computer's date and time are correct.  If "
"your clock is wrong WACoins will not work properly."),
QT_TRANSLATE_NOOP("wacoins-core", "Error: Wallet locked, unable to create transaction  "),
QT_TRANSLATE_NOOP("wacoins-core", ""
"Error: This transaction requires a transaction fee of at least %s because of "
"its amount, complexity, or use of recently received funds  "),
QT_TRANSLATE_NOOP("wacoins-core", "Error: Transaction creation failed  "),
QT_TRANSLATE_NOOP("wacoins-core", "Sending..."),
QT_TRANSLATE_NOOP("wacoins-core", ""
"Error: The transaction was rejected.  This might happen if some of the coins "
"in your wallet were already spent, such as if you used a copy of wallet.dat "
"and coins were spent in the copy but not marked as spent here."),
QT_TRANSLATE_NOOP("wacoins-core", "Invalid amount"),
QT_TRANSLATE_NOOP("wacoins-core", "Insufficient funds"),
};
